Repository zeta-chain/cli, pull requests merged in 2025-06, with the labels that each got.

#40 ci: add version
  .github/workflows/publish-npm.yaml
  src/config.json
  src/index.ts
Labels: ci

#16 fix: remove help command
  src/index.ts
Labels: fix

#42 chore: downgrade localnet before zeta v2 arch updates
  package.json
  yarn.lock
Labels: chore
